### PR TITLE
Adding playbook for administrators to get accustomed to OpenShift ins…

### PR DESCRIPTION
**Pull request by etsauer**
…talled on a host

cc: @JaredBurck @sabre1041 @trevorquinn @shah-zobair @themoosman

### CODE REVIEW

**Comment by JaredBurck** [comment]
@etsauer solid work. think this is a great overview for system admins.  especially like the storage section. would also mention the oc client tools (can be download from install.openshift.com). And not sure if there are any k8s services running, if so you may want to call those services out as well. LGTM

**Comment by etsauer** [comment]
@JaredBurck No k8s services that you'll see as they are embedded in the atomic-openshift-* stuff. where do you think the oc mention should be?

**Comment by JaredBurck** [comment]
@etsauer okay. I know you can use kubectl but didnt recall (or verify) if those services were embedded or not.  I would mention oc in the Master software section, since that is where it is installed and maybe note with a link [1] that these can be downloaded and installed on client machines.

[1] https://access.redhat.com/downloads/content/290

**Comment by etsauer** [comment]
@JaredBurck how's this?

**Comment by JaredBurck** [comment]
@etsauer that's great!

**Comment by etsauer** [comment]
@sabre1041 @oybed can one of you take a look at this?

**Comment by npoyant** [comment]
@etsauer , document looks good. Nice write up.

**Comment by broskos** [comment]
Looks good to me.

**Pull request merged**
