### PR TITLE
Adding DevOps reference guide

### PR DESCRIPTION
**Pull request by etsauer**
This is a reading list & reference guide for DevOps topics

/cc @sabre1041 @JaredBurck @trevorquinn

### CODE REVIEW

**Comment by etsauer** [comment]
Bump. Can anyone review this?

**Comment by sabre1041** [comment]
@etsauer looks good. 

Only thing might be to add a reference to "lean manufactoring" and links to the books under the Deep Dives and Further Learning

**Comment by etsauer** [comment]
@sabre1041 check now.

@trevorquinn any thoughts on this?

**Comment by sabre1041** [comment]
@etsauer lgtm

**Comment by trevorquinn** [comment]
Typo: "Pheonix". Other than that, looks good for starters.

**Comment by etsauer** [comment]
Fixed. someone other than me has to merge.

**Pull request merged**
