### PR TITLE
add information for consuming unlimited guest subscriptions

### PR DESCRIPTION
**Pull request by broskos**

### CODE REVIEW

**Comment by etsauer** [comment]
@broskos couple of comments.

1. I think we need to explain the problem a little better in the intro. For starters, I would think the title could mention something about using satellite to consume Socket-based subscriptions, since that's when this unlimited guest subs comes into play. Then I think the overview should make that association from "ok you bought socket-based subs for OpenShift" to " this means you have unlimited guest subscriptions for your hypervisors, and we're going to tell you how to manage them in Satellite"
2. The document should start with a top level heading and page metadata. Check out the style guide here: https://github.com/rhtconsulting/openshift-playbooks/blob/master/style_guide.adoc. Basically all the headings need an '=' removed.

Overall the technical content looks good, I think we just need more context to let users know when and how this applies to them.

**Comment by broskos** [comment]
Thanks @etsauer, please have another look.

**Comment by etsauer** [comment]
@broskos lgtm.

@JaredBurck can you second?

**Comment by JaredBurck** [comment]
@broskos  I reviewed the content and it LGTM.

@etsauer However, I did not actually spin up Satellite, KVM, or VMware to verify accuracy.  Do you prefer I test to verify or are we good to merge?

**Comment by etsauer** [comment]
@JaredBurck no need to test. Just go ahead and merge

**Pull request merged**
