### PR TITLE
Containerizing Redis Cluster

### PR DESCRIPTION
**Pull request by shah-zobair**

### CODE REVIEW

**Comment by shah-zobair** [comment]
@shraderdm : Any comments?

**Comment by shraderdm** [comment]
Nope, I think I'm good! It's been so long since we worked on this I barely
remember it, lol.

**Comment by etsauer** [comment]
@shah-zobair @shraderdm looking at this content, I think it would be more appropriately submitted here: https://github.com/rhtconsulting/rhc-ose/tree/openshift-enterprise-3/demos

**Comment by shah-zobair** [comment]
@etsauer : Submitted to the mentioned Repo

**Comment by etsauer** [comment]
Thanks. Closing this.

**Pull request closed without merging**
