### PR TITLE
CloudForms integration guide needs updating to be compatible with OCP 3.2/3.3 and CFME 4.1 #97

### PR DESCRIPTION
**Pull request by itewk**

### CODE REVIEW

**Comment by itewk** [comment]
@sabre1041 can you take a look at this?

**Comment by sabre1041** [comment]
@itewk: The leadership of the playbooks is being transitioned to @JaredBurck so I am going to defer this to him. 

We are also seeing URL failures in the Travis builds (most likely not related directly to this PR, but will need to be addressed before it can be merged)

@JaredBurck can you review this PR?

**Comment by itewk** [comment]
@sabre1041 and @JaredBurck yes those failures do not look related to this request.

**Comment by JaredBurck** [comment]
@itewk @sabre1041  Yes I will review this PR

**Comment by itewk** [comment]
@JaredBurck thanks for the review!

**Pull request merged**
