### PR TITLE
CloudForms/OSE integration

### PR DESCRIPTION
**Pull request by sabre1041**
CloudForms integration with OSE

@etsauer @trevorquinn @oybed @JaredBurck please review

### CODE REVIEW

**Comment by etsauer** [comment]
@sabre1041 will you add a link on the index page for the ops playbook so we can test the site?

**Comment by sabre1041** [comment]
@etsauer PR has been updated

**Comment by etsauer** [comment]
@sabre1041 index page and CF doc look good to me. I think we should add as part of this PR the link from the CF Networking doc to the CloudForms doc.

**Comment by etsauer** [comment]
Other than that.. @oybed @JayKayy @JaredBurck any further comments?

**Comment by sabre1041** [comment]
@etsauer added link on networking doc back to primary cloudforms doc

**Comment by JayKayy** [comment]
@etsauer All looks good to me

**Pull request merged**
