### PR TITLE
Adding fundamentals playbook guides

### PR DESCRIPTION
**Pull request by etsauer**
This is the first attempt at starting an OpenShift fundamentals playbook. Let me know what you think.

/cc @trevorquinn @oybed @JayKayy @sabre1041 @JaredBurck

### CODE REVIEW

**Comment by etsauer** [comment]
@JaredBurck those links are built for use in the jekyll website. they won't work in the github view. See /README for building instructions

**Comment by JaredBurck** [comment]
@etsauer didn't realize that, but now makes sense.  Docs look good and external links work!

**Comment by etsauer** [comment]
ok, that's one approver... need one more. @sabre1041 @oybed @trevorquinn ?

**Comment by sabre1041** [comment]
@etsauer looks good. my only question is around the definition of a service. Instead of a service is a set of replicated pods, maybe something along the lines of an abstraction of pods themselves. Might also want to allude to internal load balancer within OpenShift SDN

Otherwise :+1:

**Comment by etsauer** [comment]
@sabre1041 did you see that we say a lot of that stuff when we define the Service Layer down in the Implementation section? some of those things are there.

**Comment by etsauer** [comment]
Can someone else also please test the site using the jekyll build process?

**Comment by oybed** [comment]
@etsauer followed the build steps ... just a couple of minor comments from me:
- The very first yum install command outlines to use sudo, but I believe some of the following steps also need root level access, but not 100% clear which ones. 
- In my case, I didn't have a JavaScript runtime env installed, so had to install nodejs in addition to steps outlined.

**Comment by oybed** [comment]
@etsauer looking at the building blocks for OpenShift, and this may be for a follow-up PR, but it would be nice to include something around the scheduler and what the default one does v.s. maybe how to make a custom configuration for it. For the default, since you mentioned the labels and their use, it would be nice to see a mention of the pre-defined "zone" and "region".

For the diagrams: I have some diagrams created in LucidChart (some similar to the ones you already have) that we may be able to leverage in here as well - maybe with a few tweaks to make it fit.

I have noticed that customers are requesting the F5 Router plugin feature as of lately - would be nice to include that as well (could be a follow-up PR) - I have some generic (i.e.: non-customer specific) diagrams made for that already, if that would be of interest)

**Comment by sabre1041** [comment]
@etsauer validated the change looks good when using the jekyll build

**Comment by etsauer** [comment]
@oybed ok, I think from your comments, we're going to want to open the following issues for further changes:

Updates to current docs
- An update to the README build instructions
- An addition to the build blocks doc to discuss the scheduler (default behavior only i think)
- A change to improve the lucidchart images

New Guides
- An additional scheduler deep dive document
- F5 as a Router Implementation guide

I'm going to go ahead and merge, and we'll open these issues. Let me know if I've gotten this right.

**Comment by oybed** [comment]
@etsauer yes, that all looks correct and good. Thank you.

**Pull request merged**
