### PR TITLE
Validation Guide

### PR DESCRIPTION
**Pull request by etsauer**
Added a guide to validating that a new install is in good working order.

@oybed @sabre1041 @JaredBurck

### CODE REVIEW

**Comment by JaredBurck** [comment]
Great checks for validating a new install.  I would also add these additional checks ```oc get nodes```, ```oc status```, and ```openshift ex diagnostics``` for install validation.  No link to troubleshooting guide. The rest of this validation guide is good with me.

**Comment by etsauer** [comment]
@JaredBurck there is already a "Validating Nodes" section that does oc get nodes... was there something missing from that?

Otherwise I think this is good feedback and I will add it when I can

**Comment by etsauer** [comment]
@JaredBurck made some additions based on your suggestions. Please take a look.

Note: the troubleshooting guide is in progress separately, this no link yet.

**Comment by JaredBurck** [comment]
@etsauer updates look good to me. PR can be merged.  FYI, found Solution article on verifying OpenShift install [1].

[1] https://access.redhat.com/solutions/2068843

**Comment by etsauer** [comment]
Going to go ahead and merge.

**Pull request merged**
